[package]
name = "wsyscall-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
once_cell = { version = "1.19.0", features = ["alloc", "race"] }
spin = "0.9.8"

[features]
default = ["indirect"]
direct = []
indirect = []

[build-dependencies]
rand = "0.8.5"
