[package]
name = "wsyscall-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
lazy_static = { version = "1.5.0", features = ["spin_no_std"] }
spin = "0.9.8"

[features]
default = ["direct"]
direct = []
indirect = []

[build-dependencies]
rand = "0.8.5"
